// src/components/ui/Modal.jsx
import { Dialog, Transition } from "@headlessui/react";
import { Fragment } from "react";
import { twMerge } from "tailwind-merge";

export function Modal({ isOpen, onClose, centered = true, children }) {
  return (
    <Transition appear show={isOpen} as={Fragment}>
      <Dialog as="div" className="relative z-50" onClose={onClose}>
        <Transition.Child
          as={Fragment}
          enter="transition ease-out duration-200"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="transition ease-in duration-150"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <div className="fixed inset-0 bg-gray-900/80" />
        </Transition.Child>

        <div
          className={twMerge(
            "fixed inset-0 flex justify-center overflow-auto py-4"
          )}
        >
          <Transition.Child
            as={Fragment}
            enter="ease-out duration-300"
            enterFrom="opacity-0 scale-95"
            enterTo="opacity-100 scale-100"
            leave="ease-in duration-100"
            leaveFrom="opacity-100 scale-100"
            leaveTo="opacity-0 scale-95"
          >
            <Dialog.Panel className="my-auto w-[90vw] max-w-lg transform rounded-xl border border-gray-400 bg-gray-700 p-6 text-left align-middle text-gray-100 shadow-xl transition">
              {children}
            </Dialog.Panel>
          </Transition.Child>
        </div>
      </Dialog>
    </Transition>
  );
}

// src/lib/components/Modal.svelte
<script lang="ts">
  import type { createDialog } from 'svelte-headlessui'
  import { Icon, XMark } from 'svelte-hero-icons'
  import { fade, scale } from 'svelte/transition'
  import { twMerge } from 'tailwind-merge'

  export let modalStore: ReturnType<typeof createDialog>
  export let modalWindowStyles = ''
</script>

{#if $modalStore.expanded}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-surface-950/90 p-4"
    transition:fade
  >
    <div
      class={twMerge(
        'relative overflow-auto rounded-2xl border border-surface-600 bg-surface-800 p-10 shadow',
        modalWindowStyles
      )}
      transition:scale
      use:modalStore.modal
    >
      <button
        type="button"
        class="btn btn-icon btn-secondary absolute right-1.5 top-1.5"
        on:click={modalStore.close}
      >
        <Icon
          src={XMark}
          size="1.25rem"
          class="stroke-2"
        />
      </button>
      <slot />
    </div>
  </div>
{/if}
